# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='command_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1000)),
                ('code', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cmd', models.CharField(max_length=1000)),
                ('rt_value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='value_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1000)),
                ('code', models.CharField(max_length=1000)),
            ],
        ),
    ]
